development: 
 adapter: postgresql
 encoding: unicode
 database: pickflick_development
 pool: 5
 username: postgres
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: pickflick_test
 pool: 5
 username: postgres
 password: